spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: 4317
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 5000
